var a;a||(a=typeof Module !== 'undefined' ? Module : {});var e={},f;for(f in a)a.hasOwnProperty(f)&&(e[f]=a[f]);a.arguments=[];a.thisProgram="./this.program";a.quit=function(b,c){throw c;};a.preRun=[];a.postRun=[];var g="";g=__dirname+"/";var h,l;a.read=function(b,c){h||(h=require("fs"));l||(l=require("path"));b=l.normalize(b);b=h.readFileSync(b);return c?b:b.toString()};
a.readBinary=function(b){b=a.read(b,!0);b.buffer||(b=new Uint8Array(b));b.buffer||m("Assertion failed: undefined");return b};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(b){if(!(b instanceof n))throw b;});process.on("unhandledRejection",m);a.quit=function(b){process.exit(b)};a.inspect=function(){return"[Emscripten Module object]"};
var p=a.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),q=a.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||p);for(f in e)e.hasOwnProperty(f)&&(a[f]=e[f]);e=void 0;"object"!==typeof WebAssembly&&q("no native wasm support detected");var r,t=!1;"undefined"!==typeof TextDecoder&&new TextDecoder("utf8");"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
var buffer,u,v,w,x=a.TOTAL_MEMORY||16777216;5242880>x&&q("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+x+"! (TOTAL_STACK=5242880)");a.buffer?buffer=a.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(r=new WebAssembly.Memory({initial:x/65536,maximum:x/65536}),buffer=r.buffer):buffer=new ArrayBuffer(x);a.HEAP8=u=new Int8Array(buffer);a.HEAP16=new Int16Array(buffer);a.HEAP32=w=new Int32Array(buffer);a.HEAPU8=v=new Uint8Array(buffer);a.HEAPU16=new Uint16Array(buffer);
a.HEAPU32=new Uint32Array(buffer);a.HEAPF32=new Float32Array(buffer);a.HEAPF64=new Float64Array(buffer);w[15940]=5306672;function y(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c();else{var d=c.B;"number"===typeof d?void 0===c.A?a.dynCall_v(d):a.dynCall_vi(d,c.A):d(void 0===c.A?null:c.A)}}}var z=[],B=[],C=[],D=[],E=!1;function F(){var b=a.preRun.shift();z.unshift(b)}var G=Math.ceil,H=Math.floor,I=0,J=null,K=null;a.preloadedImages={};a.preloadedAudios={};
function L(){var b=M;return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}var M="a.out.wasm";if(!L()){var N=M;M=a.locateFile?a.locateFile(N,g):g+N}function O(){return new Promise(function(b){a:{try{if(a.wasmBinary){var c=new Uint8Array(a.wasmBinary);break a}if(a.readBinary){c=a.readBinary(M);break a}throw"both async and sync fetching of the wasm failed";}catch(d){m(d)}c=void 0}b(c)})}
function P(b){function c(b){a.asm=b.exports;I--;a.monitorRunDependencies&&a.monitorRunDependencies(I);0==I&&(null!==J&&(clearInterval(J),J=null),K&&(b=K,K=null,b()))}function d(b){c(b.instance)}function k(b){return O().then(function(b){return WebAssembly.instantiate(b,A)}).then(b,function(b){q("failed to asynchronously prepare wasm: "+b);m(b)})}var A={env:b};I++;a.monitorRunDependencies&&a.monitorRunDependencies(I);if(a.instantiateWasm)try{return a.instantiateWasm(A,c)}catch(T){return q("Module.instantiateWasm callback failed with error: "+
T),!1}(function(){if(a.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||L()||"function"!==typeof fetch)return k(d);fetch(M,{credentials:"same-origin"}).then(function(b){return WebAssembly.instantiateStreaming(b,A).then(d,function(b){q("wasm streaming compile failed: "+b);q("falling back to ArrayBuffer instantiation");k(d)})})})();return{}}a.asm=function(b,c){c.memory=r;c.table=new WebAssembly.Table({initial:146,maximum:146,element:"anyfunc"});return P(c)};
function Q(){a.___errno_location&&(w[a.___errno_location()>>2]=12)}var R=a.asm({},{c:function(b,c,d){v.set(v.subarray(c,c+d),b)},a:function(b){b=+b;return 0<=b?+H(b+.5):+G(b-.5)},b:function(b){b|=0;var c=u.length|0;var d=w[15940]|0;var k=d+b|0;if(0<(b|0)&(k|0)<(d|0)|0>(k|0))return m("OOM"),0,Q(),-1;if(b=(k|0)>(c|0))m("OOM"),b=!0;if(b)return Q(),-1;w[15940]=k|0;return d|0}},buffer);a.asm=R;a.___wasm_call_ctors=function(){return a.asm.__wasm_call_ctors.apply(null,arguments)};
a._hb_blob_create=function(){return a.asm.d.apply(null,arguments)};a._hb_blob_destroy=function(){return a.asm.e.apply(null,arguments)};a._free=function(){return a.asm.f.apply(null,arguments)};a._hb_blob_get_length=function(){return a.asm.g.apply(null,arguments)};a._malloc=function(){return a.asm.h.apply(null,arguments)};a._hb_buffer_create=function(){return a.asm.i.apply(null,arguments)};a._hb_buffer_destroy=function(){return a.asm.j.apply(null,arguments)};
a._hb_buffer_set_direction=function(){return a.asm.k.apply(null,arguments)};a._hb_buffer_get_length=function(){return a.asm.l.apply(null,arguments)};a._hb_buffer_get_glyph_infos=function(){return a.asm.m.apply(null,arguments)};a._hb_buffer_get_glyph_positions=function(){return a.asm.n.apply(null,arguments)};a._hb_buffer_guess_segment_properties=function(){return a.asm.o.apply(null,arguments)};a._hb_buffer_add_utf8=function(){return a.asm.p.apply(null,arguments)};
a._hb_face_create=function(){return a.asm.q.apply(null,arguments)};a._hb_face_destroy=function(){return a.asm.r.apply(null,arguments)};a._hb_font_create=function(){return a.asm.s.apply(null,arguments)};a._hb_font_destroy=function(){return a.asm.t.apply(null,arguments)};a._hb_font_set_scale=function(){return a.asm.u.apply(null,arguments)};a._hb_shape=function(){return a.asm.v.apply(null,arguments)};a.___errno_location=function(){return a.asm.w.apply(null,arguments)};
a.dynCall_vi=function(){return a.asm.x.apply(null,arguments)};a.asm=R;function n(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}n.prototype=Error();n.prototype.constructor=n;K=function S(){a.calledRun||U();a.calledRun||(K=S)};
function U(){function b(){if(!a.calledRun&&(a.calledRun=!0,!t)){E||(E=!0,y(B));y(C);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var b=a.postRun.shift();D.unshift(b)}y(D)}}if(!(0<I)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)F();y(z);0<I||a.calledRun||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):
b())}}a.run=U;function m(b){if(a.onAbort)a.onAbort(b);void 0!==b?(p(b),q(b),b='"'+b+'"'):b="";t=!0;throw"abort("+b+"). Build with -s ASSERTIONS=1 for more info.";}a.abort=m;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();a.noExitRuntime=!0;U();
